### ISSUE TITLE
Add plugin to spigot resources

### ISSUE THREAD

**Issue by TutorialMan7727** [Strafbefehl/DeluxeHubReloaded#1]
Hello, I was wondering if you could add this plugin to the spigot resources (plugin list)

**Comment by Strafbefehl** [comment]
Hey, I guess I am not allowed to. Correct me if I am wrong.
![image](https://github.com/user-attachments/assets/a99c486a-1b35-46a9-b702-4f8a13a00cbf)

**Comment by TutorialMan7727** [comment]
I think it is more refering to other people uploading e.g. if I wad to upload this plugin. I have seen other reloaded plugins on the list but I am no expert and will open an discussion on the spigot forums.

**Comment by TutorialMan7727** [comment]
Cool, Thank you
