### ISSUE TITLE
Which version should I use for 1.20.5 or 1.20.6?

### ISSUE THREAD

**Issue by konsheng** [Strafbefehl/DeluxeHubReloaded#3]
Which version should I use for 1.20.5 or 1.20.6?

**Comment by TheFaik** [comment]
> Какую версию мне следует использовать для 1.20.5 или 1.20.6?

2-ой файл
![изображение](https://github.com/user-attachments/assets/530d012f-0780-40ba-9b1c-8a192000c07b)

**Comment by Strafbefehl** [comment]
There is no 1.20.5 and 1.20.6 version at the moment but I create one for you today:)

**Comment by Strafbefehl** [comment]
> > Какую версию мне следует использовать для 1.20.5 или 1.20.6?
> 
> 2-ой файл ![изображение](https://private-user-images.githubusercontent.com/99492973/358899964-530d012f-0780-40ba-9b1c-8a192000c07b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5Nzk5MDMsIm5iZiI6MTcyMzk3OTYwMywicGF0aCI6Ii85OTQ5Mjk3My8zNTg4OTk5NjQtNTMwZDAxMmYtMDc4MC00MGJhLTliMWMtOGExOTIwMDBjMDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDExMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzIwNDkxMWNhYzQyY2Y2ZWNiNzkyNzI4NjVhMWFiM2U1MDFlODM1MGU5N2FmMzdiZTVjYzFlOTY1MGI1MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BtxoLssST22tYD1RTeeiB1mCB1vY9jIg1rEDDDfihY8)

This was a mistake it should be 1.21-1.21.1 I corrected it

**Comment by Strafbefehl** [comment]
@konsheng I published the 1.20.5 and 1.20.6 version:)

https://github.com/Strafbefehl/DeluxeHubReloaded/releases/tag/v3.6.0
![image](https://github.com/user-attachments/assets/fd62b3fa-c253-495c-8cdd-68bfdf165dcd)

**Comment by konsheng** [comment]
okey
