### ISSUE TITLE
How do I migrate config from DeluxeHub?

### ISSUE THREAD

**Issue by jungltemple** [Strafbefehl/DeluxeHubReloaded#7]
Is it automatic or something?
I have a 1.20.1 server that I've been wanting to update for a while. I tried 1.21.1 but that's still too unstable, so now I'm going to update to 1.20.6. Do I need to copy the old config manually or does it simply automatically copy?

**Comment by Strafbefehl** [comment]
Hey, sorry for my late answer maybe you already figure it out that everything happened automatically after you dropped your files in the new plugin folder

**Comment by jungltemple** [comment]
Thank you.
